experiment_name: cxr_debug
experiment_dir: experiments/debug_run

pairs_csv: data/pairs/cxr_consistency_pairs.csv

tokenizer_name: microsoft/BiomedVLP-CXR-BERT-specialized

image_encoder_name: efficientnet_b0
text_encoder_name: cxrbert

pretrained_image: true

freeze_image_encoder:  true
freeze_text_encoder: false

image_size: 224
max_length: 128

projection_dim: 256
dropout: 0.3

batch_size: 16

epochs: 20

learning_rate: 1e-4
weight_decay: 1e-4

num_workers: 0

max_train_samples: 20000
max_valid_samples: 4000

log_batch_loss: false
log_every_steps: 100